version: "3.8"
networks:
    app-tier:
        driver: bridge
services:
    mysqldb:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        expose:
            - "3306"
        ports:
            - "3306:3306"
        networks:
            - app-tier
        environment:
            - MYSQL_ROOT_PASSWORD=lovedubcars
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes 
    node:
        depends_on: 
            - mysqldb
        build: .
        command: 'npm start'
        ports:
            - "3000:3000"
        networks:
            - app-tier

volumes:
    mysql:
    mysql_config: